### PR TITLE
Phil/schemalate code quotes

### LINKED ISSUE #369: Docusaurus doesn't like flowctl-rs output (+ one more json>md suggestion)
Been getting acquainted with markdown generation commands. They're already quite useful for me as a resource when writing the docs. However, it's not ready to just copy-and-paste because the tagging and unicode crashes docusaurus output (although, as we can see here, github is just fine with it). 

 An example of the `source-postgres` connector spec to illustrate:

ran `flowctl api spec --image=ghcr.io/estuary/source-postgres:dev | jq '.endpointSpecSchema' | flowctl-rs schema-to-markdown > endpoint-docs.md` as directed

Which produced  output formatted like:

| Location | Title | Description | Type | Default |
|---|---|---|---|---|
| *<code></code>* |  |  | object | <code></code> |
| *<code>&#x2F;database</code>* |  | Logical database name to capture from. | string | <code>&quot;postgres&quot;</code> |
| *<code>&#x2F;host</code>* |  | Host name of the database to connect to. | string | <code></code> |
| <code>&#x2F;networkProxy</code> |  | Configurations to enable network proxies. | object | <code></code> |
| <code>&#x2F;networkProxy&#x2F;proxyType</code> |  | The type of the network proxy. Supported types are: ( sshForwarding ) | string | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding</code> |  | Config for proxy of type sshForwarding | object | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;localPort</code> |  | Local port to start the SSH tunnel. The connector should fetch data from localhost:&lt;local&#x5F;port&gt; after SSH tunnel is enabled. | integer | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;remoteHost</code> |  | Host name to connect from the remote SSH server to the remote destination (e.g. DB) via internal network. | string | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;remotePort</code> |  | Port of the remote destination. | integer | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;sshEndpoint</code> |  | Endpoint of the remote SSH server that supports tunneling | string | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;sshPrivateKeyBase64</code> |  | Base64-encoded private Key to connect to the remote SSH server. | string | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;sshUser</code> |  | User name to connect to the remote SSH server. | string | <code></code> |
| ~~_<code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;&#x2A;</code>_~~ |  |  |  | <code></code> |
| ~~_<code>&#x2F;networkProxy&#x2F;&#x2A;</code>_~~ |  |  |  | <code></code> |
| *<code>&#x2F;password</code>* |  | User password configured within the database. | string | <code></code> |
| *<code>&#x2F;port</code>* |  |  | integer | <code>5432</code> |
| <code>&#x2F;publicationName</code> |  | The name of the PostgreSQL publication to replicate from. | string | <code>&quot;flow&#x5F;publication&quot;</code> |
| <code>&#x2F;slotName</code> |  | The name of the PostgreSQL replication slot to replicate from. | string | <code>&quot;flow&#x5F;slot&quot;</code> |
| *<code>&#x2F;user</code>* |  | Database user to use. | string | <code>&quot;postgres&quot;</code> |
| <code>&#x2F;watermarksTable</code> |  | The name of the table used for watermark writes during backfills. | string | <code>&quot;public.flow&#x5F;watermarks&quot;</code> |
| ~~_<code>&#x2F;&#x2A;</code>_~~ |  |  |  | <code></code> |

To get docsaurus to not freak out, you have to remove all unicode and tagging here. It's pretty time consuming to pick through. 

----

+ one more suggestion: Nested conflg (in this case, network proxy) might be better for docs (IMO) if broken out into a separate table rather than how it is handled here. Not a big deal if that's hard to implement.

### PR DESCRIPTION
**Pull request by psFried**
**Description:**

Fixes #369 

**Workflow steps:**

Here's an example of a command that I ran, and the table that it generated:

```shell
flowctl api spec --image ghcr.io/estuary/source-kinesis:dev | jq '.endpointSpecSchema' | flowctl schemalate markdown --exclude ''
```

Generated table:

| Property | Title | Description | Type | Required/Default |
|---|---|---|---|---|
| **`/awsAccessKeyId`** | AWS Access Key ID | Part of the AWS credentials that will be used to connect to Kinesis | string | Required, `"example-aws-access-key-id"` |
| **`/awsSecretAccessKey`** | AWS Secret Access Key | Part of the AWS credentials that will be used to connect to Kinesis | string | Required, `"example-aws-secret-access-key"` |
| `/endpoint` | AWS Endpoint | The AWS endpoint URI to connect to, useful if you&#x27;re capturing from a kinesis-compatible API that isn&#x27;t provided by AWS | string |  |
| **`/region`** | AWS Region | The name of the AWS region where the Kinesis stream is located | string | Required, `"us-east-1"` |

**Documentation links affected:**

We might want to try using this updated version to re-generate the tables in the connector docs, so they're all consistent, but no impact apart from that.

**Notes for reviewers:**

I tried to make the output look more like what we have currently in the docs, since that's the main use case we're targeting with this feature.

---
This change is [Reviewable](https://reviewable.io/reviews/estuary/flow/401)

### CODE REVIEW

**Comment by oliviamiannone** [comment]
The output looks great - no changes I feel strongly about making. The only thing is when I throw this into docusaurus, it _does_ still render the bolding on the required fields. It's redundant with the column value you added, but I suppose extra emphasis doesn't hurt 
image

**Review by oliviamiannone — APPROVED** [review]

**Comment by psFried** [comment]
> it does still render the bolding on the required fields

@oliviamiannone Yea, I had told you that the bold required fields weren't working, but that wasn't right. What was actually happening is that `bold` was implemented by surrounding the text with a single `*`, which actually made it italic, but was just kinda barely detectable with that font. So I emboldened our code that emboldens the code, and now the `code` is **`bold`** :upside_down_face:

File: crates/schemalate/src/markdown.rs [hunk 1]
```diff
@@ -79,3 +161,23 @@ fn md_escape(s: &str) -> String {
...
+mod test {
+    use super::*;
+
+    #[test]
+    fn code_containing_backtics_is_surrounded_with_more_backtics() {
+        assert_code_format(r#"foo with ` a backtic"#, r#"``foo with ` a backtic``"#);
+        assert_code_format(r#"foo with no backtic"#, r#"`foo with no backtic`"#);
+        assert_code_format(
+            r#"foo `` with ``````` many backtic`s"#,
+            r#"````````foo `` with ``````` many backtic`s````````"#,
```
Comment (mdibaiee) [inline crates/schemalate/src/markdown.rs:175]: 🥴
