### PR TITLE
network-tunnel: better error when consuming config fails

### LINKED ISSUE #648: Crummy error message when connector network proxy fails to connect
The `flow-connector-proxy` is producing a pretty confusing error message whenever a task uses the network proxy and it fails to connect. This is because of an `.expect("failed to start network tunnel")`. This should instead return a Result containing an Error that can be rendered as a clearer error message.

Example of what happens today:
```
Waiting for logs...
ERRO[0001] connector-proxy failed                        error="IOError(Custom { kind: Other, error: "task panicked" })" logSource="connector stderr" operation=validate
ERRO[0001] connector failed                              error="exit status 1" logSource="ghcr.io/estuary/materialize-postgres:v2" operation=validate
file:///flow.json error at /materializations/estuary~1wikipedia-postgres :
driver error while validating materialization estuary/wikipedia-postgres

Caused by:
    driver.Validate: exit status 1 with stderr:
    
    thread 'tokio-runtime-worker' panicked at 'failed to start network tunnel: NetworkTunnelError(BadDestinationAddress("database-4.ccpi9kwz3vei.us-east-1.rds.amazonaws.com"))', crates/connector_proxy/src/interceptors/network_tunnel_materialize_interceptor.rs:24:14
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    {"timestamp":"2022-08-24T20:16:43.372438479Z","level":"ERROR","error":"IOError(Custom { kind: Other, error: "task panicked" })","message":"connector-proxy failed"}
    
FATA[0006] fatal error                                   err="1 build errors"
```

### PR DESCRIPTION
**Pull request by mdibaiee**
**Description:**

- Resolves #648 by replacing the `.expect` with a proper `Result::Err`

**Workflow steps:**

- wrongly-configured network tunnel for a materialization

**Documentation links affected:**
N/A

**Notes for reviewers:**

(anything that might help someone review this PR)

- - -
This change is [Reviewable](https://reviewable.io/reviews/estuary/flow/664)

### CODE REVIEW

File: crates/connector_proxy/src/interceptors/network_tunnel_capture_interceptor.rs [hunk 1]
```diff
@@ -23,7 +23,7 @@ impl NetworkTunnelCaptureInterceptor {
             )
             .await
             .map_err(|err| {
-                create_custom_error(&format!("error consuming tunnel configuration {:?}", err))
+                create_custom_error(&format!("error starting network tunnel {:?}", err))
```
Comment (willdonnelly) [inline crates/connector_proxy/src/interceptors/network_tunnel_capture_interceptor.rs:26]: Should this substitution ("consuming tunnel configuration" -> "starting network tunnel") maybe be applied to the other `adapt_*` functions as well?

**Review by willdonnelly — APPROVED** [review]
LGTM

File: crates/connector_proxy/src/interceptors/network_tunnel_capture_interceptor.rs (hunk 1 above)
Comment (mdibaiee) [reply crates/connector_proxy/src/interceptors/network_tunnel_capture_interceptor.rs:26]: Yes, I didn't notice the others, updated ✅
