### PR TITLE
crates/doc: properly identify integer => numeric schema changes

### LINKED ISSUE #1522: inferred schema updates not emitted for `format: integer -> number` widening
The runtime is failing to emit `inferred schema updated` logs when the inferred schema is in fact updated. This was observed and reproduced in the specific scenario of a widening from `type: string, format: integer` to `type: string, format: number`.

### PR DESCRIPTION
**Pull request by jgraettinger**
Previously, the schema inference logic could silently swallow change detection for integer locations which are widenend to fractional values.

Fixes #1522 

**Workflow steps:**

(How does one use this feature, and how has it changed)

**Documentation links affected:**

(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, along with a brief description)

**Notes for reviewers:**

(anything that might help someone review this PR)

- - -
This change is [Reviewable](https://reviewable.io/reviews/estuary/flow/1523)

### CODE REVIEW

File: crates/doc/src/shape/widen.rs [hunk 1]
```diff
@@ -1118,6 +1122,30 @@ mod test {
         assert_eq!(length_bounds((1 << 33) + 1), (1 << 31, u32::MAX)); // Saturates as u32::MAX.
     }
 
+    #[test]
+    fn test_widening_numeric() {
+        let schema = r#"
+            type: []
+        "#;
+        // We preserve an enum if it's only widened with strings and exact matches.
```
Comment (psFried) [inline crates/doc/src/shape/widen.rs:1130]: copypasta comment?

**Review by psFried — APPROVED** [review]
LGTM
Good catch on the minimum/maximum getting reset, too.
